### ISSUE TITLE
Still running?

### ISSUE THREAD

**Issue by darcyclarke** [nodeschool/nyc#27]
Hey there,

I'm a NodeSchool organizer from Toronto & am at #NodeSummit right now with @eaharonoff who's wondering if you are still running events(?). Looks like the last one was in February. He's saying he'd love to get involved somehow as well, I'm available to provide any kind of support if your having trouble finding sponsors/volunteers. 

Hope this finds you well!

Cheers,
Darcy

**Comment by gautamarora** [comment]
hey @darcyclarke & @eaharonoff - thanks for checking. We are very much alive; had taken a short break after ~2 years of regular monthly nodeschools. Infact, we had our organizers meeting today, and have put together a plan for events starting august.

Thanks so much for offering to help. We're looking good with sponsors/venue for now, but are always looking for mentors. You can join us at bit.ly/nyjs-slack and ping me (my username is gautam on the slack), and I will set you up to be a mentor for our next event.

Hope you're enjoying #NodeSummit!

**Comment by eaharonoff** [comment]
thanks @darcyclarke! I'll go ahead and do that...

**Comment by joesepi** [comment]
Hi there. How is this planning going? I'm curious as I've been wanting to start doing regular nodeschools in NYC as well. Thanks!

**Comment by gautamarora** [comment]
@joesepi - the last nodeschool we ran was on 09/14/2017. We ran it using the electron nodeschool and then had a mini hackathon + demo session at the end. Pics from the event are here: https://twitter.com/gautam/status/908513585948741633

We've been moving office buildings, so that had put the last few months on hold from a venue pov. We tried seeing if we could move to @eaharonoff's office, but that didn't work out either. As the office move has now completed, we will be able to resume hosting NodeSchool at Conde Nast offices from January 2018.

I would love to get some help in co-organizing the event at Conde Nast offices or at other locations in NYC. Whats worked great for us earlier is to put together a longer term plan (6 months into the future). Do you want to work together on that?

**Comment by joesepi** [comment]
@gautamarora yes. I'd love to work together on 2018 Nodeschools. Please include me in the next planning meeting or let's find time for the two of us to catch up and go from there. I lead developer advocacy efforts for IBM in NYC and I am looking to do more of these types of events as well as "get into open source" types of events. And I am all for partnering with others in making these things happen and making them great events. Thanks!

**Comment by gautamarora** [comment]
wonderful @joesepi. I also gathered some folks from the NYJS community that have been past mentors and are looking to step up and help with organizing the events at a regular cadence. I will setup sometime for all of us to connect and plan the 2018 nodeschool events!

**Comment by gautamarora** [comment]
I've started #28 to start discussions for 2018 planning. Closing this with, "Yes, we are still running" :)
