### ISSUE TITLE
Regular nodeschool sessions

### ISSUE THREAD

**Issue by gautamarora** [nodeschool/nyc#4]
Wanted to share a quick update on the recent nodeschool nyc events, and get the conversations started here again.

@acingraham & jovena whatmoor have been organizing nodeschool regularly as part of the ny javascript meetup, & i'll be joining them as a co-organizer of the meetup.
http://www.meetup.com/NY-JavaScript/

We've secured a venue (Conde Nast, 222 Broadway) to host nodeschool for the rest of the year, and also want to start working on the stickers and website (will add new issues for that to get feedback)

Any input/feedback/comments you have will be great. We're excited to make nodeschool a regular monthly event.

**Comment by hackygolucky** [comment]
I would love to help take part in this. I've enjoyed running nodeschool events in the past http://hackygolucky.com/2014/03/02/pdxnode-presents-nodeschool/ and would love to bring this energy to the NYC events. Let me know how I can help!

I'd recommend trying to get other Node meetups in the city and maybe organizers/attendees/local speakers from EmpireNode(I can help with this since I am one of the people who started it) involved. It would build out a super hearty group!

**Comment by gautamarora** [comment]
@hackygolucky we'd love to have you join us as a mentor for the next nodeschool on 09/24. You can sign up over here: http://www.meetup.com/NY-JavaScript/events/224933312/
